const RULES = `RULES (hard): write code immediately, do not summarize the brief. Agents never commit; LEAVE ALL CHANGES UNSTAGED (never git add); journal to the named dir; retained artifacts (/home/erikg/sxgc-466, /tmp/rpfbwt-64-466, all .sxi/.sxi2, /mnt/nvme3n1 references) are READ-ONLY; kill nothing but your own pids; stay under your RAM budget; a run that cannot honestly pass a gate reports the failure instead of hiding it; report live long-run PIDs in your final message so the supervisor can adopt them.`;
return await runs.all([
  { key: 'crosslcpImpl', agent: 'coder', model: 'lunaroute/glm-5.3', task: `THE CROSS-LCP MERGE - the project's last big engineering problem (the pile's only blocker). Design is LOCKED - read bit6/sxi_logs/cross-lcp/DESIGN.md and RESULTS.md FIRST (the measurement lane already banked: max cross-LCE 96,914 symbols, conditional two-candidate cost 23.7 symbols/run, dictionary anchors cover only 0.0603% - the design is bounded fingerprints + certified phrase shortcuts, NOT dict-anchor shortcuts).
GOAL: a pairwise rleBWT merge that costs O(runs x LCE-budget), NOT per-character: place chunk B's runs among chunk A's runs using bounded fingerprint LCE comparisons (the SLIM_FP probe machinery in bit6/slim_lce.hpp is the reference for hash-probe LCE with journaled budgets), then emit the merged four files.
BUILD: bit6/cross_lcp_merge.cpp. Inputs: two chunk front-end dirs (the SXCR chunk format from bit6/chunk_frontend.cpp; 16 fragment chunks exist at /home/erikg/sxgc/vendor/chunk-merge-v3/chunks - regenerable in ~270s via the banked chunk_frontend if needed). Output: merged four files (rlebwt/meta/ssa/ssa_t) in the SAME format the batch-BCR merge produces (bit6/chunk_bcr_merge.cpp output format).
GATES: (a) SMALL: the banked test suites (bit6/sxi_logs/chunk-merge-v3/test_chunk_bcr_merge.py pattern) - merged == direct BCR, four files, 20+ synthetic collections; (b) the FULL 16-chunk sequence: four-file byte-identity + endpoints/slim/chi printing chi = 306164765 (the finish sequence is banked at bit6/sxi_logs/chunk-merge-v3/finish_gate.sh + the dictionary symlink trick: the endpoints binary needs <prefix>.dict - symlink the reference parse files, see chunk-merge-v3 history); (c) THE COST TABLE: per-pair merge wall + total wall vs batch-BCR's banked 20,599s serial / 19,597s tree - the WHOLE POINT is beating per-character insertion; record symbols-compared counts from the journaled budgets.
If the O(runs x LCE) merge cannot be made exact (cyclic cross-boundary order needs the FULL LCE when fingerprints collide - budget-journal every full-LCE fallback), say so honestly with the failing fixture - a bounded-approximation merge is NOT acceptable, only exact.
` + RULES + `
Journal to bit6/sxi_logs/cross-lcp-impl/. RAM budget 200 GB.` },
  { key: 'forksExtract', agent: 'coder', model: 'lunaroute/glm-5.3', task: `THE FORK-MATRIX EXTRACTOR (paper two: the chi genotyping platform). SPEC (ratified): the matrix is STRING x (WITNESS, CLASS) BINARY PRESENCE - for each chi witness and each coverage class realized at that witness, a column records which strings realize that class there (a string may appear in MULTIPLE classes at one witness - that is the honest semantics; do NOT force single-class).
READ FIRST: bit6/sxi_logs/forks/REPORT.md (the feasibility audit - it found the blockers this spec fixes) and docs/GWAS_FORK_MATRIX.md. ARTIFACT REALITY: the 466 milestone artifact is SXI1 (format at bit6/sxi_write.cpp; reader xsa/src/sxi.rs) - it HAS the ssa/ssa_t members (run head/tail SA samples) - extract from SXI1 directly. For yeast the audit used /mnt/nvme3n1/erikg/sxgc-yeast/grl/ (corpus + names.tsv) and the SXI2 at /mnt/nvme3n1/erikg/sxi2-v5/yeast235.sxi2.
BUILD: xsa forks --jsonl <sxi> [--n N] [-o out.jsonl]: stream witnesses in text order; per witness: resolve the run(s) whose interval witnesses it (the witness is an END-positioned context event - check the audit's findings + lean/Sxgc.lean requirement semantics); for each distinct next-symbol class among the witness's occurrences, emit {witness, class_id, char, strings: [string ids]} - use the ssa/ssa_t samples + names.tsv (string id = which collection member the text position falls in; boundaries via the names/offsets sidecar).
GATES: (a) YEAST FULL: records consistent with chi=85,404,336 witnesses; every witness emits >=1 class; spot-verify 100 witnesses by direct text check (the audit's model_audit.py shows the sidecar-bounded corpus reading); (b) 466 PREFIX SMOKE: xsa forks --n 10000000 over /home/erikg/sxgc-466/milestone/hprc.sxi (52 GB, READ-ONLY) - record throughput, RAM, projected full-466 wall and output bytes; (c) GWAS SMOKE: yeast matrix + simulated phenotypes (inject association at ~20 loci across ~100 strings) -> chi-square per column -> recovery/power vs random columns (pure python OK).
` + RULES + `
Journal to bit6/sxi_logs/forks-extract/. RAM budget 400 GB (the 466 artifact mmap).` },
  { key: 'minimality4', agent: 'coder', model: 'lunaroute/glm-5.3', task: `THE LAST SORRY: the minimality lower half (|scan| <= chi T, Lemma 34 tie-breaking) - the only live sorry in lean/Sxgc.lean (~line 7580, under the 'REMAINING' comment). Two prior campaigns failed honestly: read lean/FLEET_MINIMALITY_REPORT.md (the O2/O3/O4 route has counterexamples under modified scan caps - do NOT re-attempt that route as-is) and lean/FLEET_O1_REPORT.md (the covering half IS proven - your target is only the lower bound).
THE WEDGE (new idea required, hinted by the data): the duplicate-family characterization (lean/counterexamples/o1_saturation_family.* - duplicates arise only under small scan caps; at FULL scan length the scan saturates, 0 counterexamples across 729 exhaustive + 320 random texts). Candidate routes: (a) prove saturation directly - at full scan cap, the emitted classes are exactly the maximal coverage classes (chi_eq_maxClasses in lean/SxgcRevival.lean + the class machinery may give the injection); (b) an injection from scan-emitted positions into max-classes with tie-breaking handled by saturation; (c) if (a)/(b) fail, prove the WEAKER saturated-regime statement and characterize the boundary - statement-lock what remains.
GATES: sorry count at the target decreases or a precise statement-locked missing lemma; zero new axioms; existing statements byte-identical; lake -d <worktree>/lean build green; the BIT gate (sxgctest) green; the two RETIRED false sorries stay untouched.
` + RULES + `
Journal to lean/FLEET_MINIMALITY4_REPORT.md. RAM budget 64 GB.` },
  { key: 'paper', agent: 'coder', model: 'lunaroute/glm-5.3', task: `PAPER REFRESH - insert the banked results into paper/main.tex with EXACT numbers, NO new claims, no adjectives the data does not support. Read RESEARCH.md's entries from 'THE 466 FROM-ZERO MILESTONE' onward plus paper/main.tex, then edit:
(1) The 466 number is FROM-ZERO REPRODUCIBLE: chi(HPRC-466) = 2,250,211,129 reproduced by an independent full construction with byte-identical artifacts (sha256 2aca539e3747414e447372b9554f14613335162fd07c00c03599a1948198a8fb, 52,175,300,288 bytes, 27.15 h, one command) - remove 'validation-only' qualifiers if present.
(2) Construction multiplicity: chi=306,164,765 (n=1,082,130,213, R=397,723,010) has FIVE byte-identical constructions (PFP monolithic, PFP regenerated, BCR differential, serial batch-merge, parallel merge tree).
(3) Theory additions (cite Lean file names): covering closed (covering_given_stream via runEdgeDominate_true, SxgcRunEdge.lean); witness revival + chi-count demotion (SxgcRevival.lean, SxgcChiMono.lean: chi_append_decreases - chi NOT monotone under append, demotion-driven); the unique-delimiter corollary (SxgcUniDelim.lean: chi_append_unique_last); criterion C bridge (a) (SxgcPhi.lean: primitive => distinct rotations).
(4) Container results (honest): v5 format - pile-frag 2.61 GB (0.502x of the prior form, phi 42.25 bits/run) with warm HTTP FASTER (0.325 vs 0.362 ms); yeast 0.924 GB, k10 20.22 GB; the association floor is honest at ~42 bits/run (the 25-30 preflight assumed a compressible run permutation - refuted, RESEARCH.md #19); witness-anchored locate (mems --first): 11x vs full locate on yeast, 1000/1000 positions verified.
(5) An honest negative-results paragraph: stable interleave merges impossible (counterexamples banked); witness-restricted run structures break backward search (v7 model, 99-100% query fallback); the run permutation is incompressible (Golomb = flat on real corpora).
CONSTRAINTS: match the paper's existing macros/style; every number must match RESEARCH.md exactly; do not touch theorem statements; keep \\hprcchi and existing macros consistent; latex must compile (pdflatex if available, else syntax-check braces/environments).
` + RULES + `
Journal to bit6/sxi_logs/paper-refresh/. RAM budget 16 GB.` }
]);
