#!/usr/bin/env python3
"""Produce reviewable tables and conditional extrapolations from retained JSONL."""
import json
import math
import csv
from pathlib import Path

HERE = Path(__file__).resolve().parent
rows = [json.loads(line) for line in (HERE/'measurements.jsonl').read_text().splitlines()]
config = next(r for r in rows if r['type'] == 'configuration')
boundaries = [r for r in rows if r['type'] == 'boundary']
dicts = [r for r in rows if r['type'] == 'dictionary']
assert len(boundaries) == len(dicts) == 15 and rows[-1]['type'] == 'complete'
assert [r['boundary'] for r in boundaries] == list(range(15))
assert [r['boundary'] for r in dicts] == list(range(15))
assert rows[-1]['work'] <= config['total_work_budget']
with (HERE/'histograms.csv').open('w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['boundary', 'population', 'inclusive_upper_edge', 'count'])
    for row in boundaries:
        for population in ('predecessor', 'successor', 'best', 'both', 'search'):
            writer.writerows((row['boundary'], population, edge, count) for edge, count in
                             zip(config['histogram_upper_edges'], row[population]['bins']))
for row in boundaries:
    assert row['samples'] == config['samples_per_boundary']
    for key in ('predecessor', 'successor', 'best', 'both', 'search'):
        h = row[key]
        assert sum(h['bins']) == h['count']
        assert 0 <= h['gt1000000'] <= h['gt10000'] <= h['gt100'] <= h['count']
    assert row['both']['count'] == row['predecessor']['count'] + row['successor']['count']
    assert row['both']['sum'] == row['predecessor']['sum'] + row['successor']['sum']
    assert row['both']['count'] <= 2*row['samples']
    assert row['best']['count'] == row['samples']
    assert not row['both']['equal_infinite'], 'Infinite periodic equality requires separate cost treatment'

R = 4.8e11
sum_runs = sum(row['b_runs'] for row in boundaries)
weights = [row['b_runs']/sum_runs for row in boundaries]
weighted = lambda fn: sum(w*fn(r) for w,r in zip(weights,boundaries))
mean_pair = weighted(lambda r:r['both']['sum']/r['samples'])
mean_best = weighted(lambda r:r['best']['sum']/r['samples'])
mean_search = weighted(lambda r:r['search']['sum']/r['samples'])
mean_queries = weighted(lambda r:r['lce_queries']/r['samples'])
mean_probes = weighted(lambda r:r['hash_probes']/r['samples'])
seconds_per_head = weighted(lambda r:r['seconds']/r['samples'])
var_mean = 0.0
for w,r in zip(weights,boundaries):
    n = r['samples']
    s = r['both']['sum']
    sample_var = max(0.0, (r['pair_cost_sum_squares'] - s*s/n)/(n-1))
    var_mean += w*w*sample_var/n
se = math.sqrt(var_mean)
model = {
    'pile_R':R, 'sampled_B_heads':sum(r['samples'] for r in boundaries),
    'adjacent_B_runs':sum_runs, 'weighted_mean_best_LCE':mean_best,
    'weighted_mean_sum_two_candidate_LCE':mean_pair,
    'weighted_mean_pair_standard_error_iid':se,
    'conditional_pile_two_candidate_symbols':R*mean_pair,
    'conditional_pile_best_candidate_symbols':R*mean_best,
    'weighted_mean_search_LCE_sum':mean_search,
    'weighted_mean_actual_LCE_calls_per_head':mean_queries,
    'weighted_mean_actual_hash_probes_per_head':mean_probes,
    'conditional_pile_search_hash_probes':R*mean_probes,
    'conditional_fragment_rate_pile_seconds':R*seconds_per_head,
    'conditional_two_candidate_days_at_1e8_symbols_per_second':R*mean_pair/1e8/86400,
    'conditional_two_candidate_days_at_1e9_symbols_per_second':R*mean_pair/1e9/86400,
    'per_boundary_zero_tail_95_upper':1-math.pow(.05,1/config['samples_per_boundary']),
    'not_fully_verified_queries':sum(r['not_fully_verified_queries'] for r in boundaries),
    'seam_candidate_pairs':sum(r['seam_candidate_pairs'] for r in boundaries),
    'aligned_phrase_pair_fraction':sum(r['aligned_phrase_pairs'] for r in boundaries)/sum(r['both']['count'] for r in boundaries),
    'aligned_phrase_bytes_fraction_of_pair_LCE':sum(r['aligned_phrase_bytes'] for r in boundaries)/sum(r['both']['sum'] for r in boundaries),
    'next_phrase_bytes_fraction_of_pair_LCE':sum(r['reached_next_phrase_bytes'] for r in boundaries)/sum(r['both']['sum'] for r in boundaries),
}
(HERE/'cost-model.json').write_text(json.dumps(model,indent=2)+'\n')
lines = ['# Cross-LCP measured results', '',
         'Generated by `summarize.py` from `measurements.jsonl`; no corpus access.', '',
         f'Each row samples {config["samples_per_boundary"]:,} B run heads with replacement. The tail below is for',
         'the **larger LCE of the two nearest A run endpoints** for each sampled head.',
         'Means for both candidates add predecessor and successor work per B head.', '',
         '| A→B | Mean max LCE | Mean two-candidate sum | Maximum | >100 | >10,000 | >1,000,000 | Seconds |',
         '|---|---:|---:|---:|---:|---:|---:|---:|']
for r in boundaries:
    h=r['best'];n=r['samples']
    lines.append(f"| {r['boundary']}→{r['boundary']+1} | {h['sum']/n:.3f} | {r['both']['sum']/n:.3f} | {h['max']:,} | {h['gt100']/n:.5%} | {h['gt10000']/n:.5%} | {h['gt1000000']/n:.5%} | {r['seconds']:.2f} |")
lines += ['', 'Full histograms (counts, including both candidates separately) are retained',
          'in `measurements.jsonl`. Bins have inclusive upper edges',
          '`0,1,4,16,64,100,1000,10000,100000,1000000,10000000,infinity`.', '',
          '| A→B | A distinct | B distinct | Shared distinct | Jaccard | Shared B occurrences | Shared B contribution bytes | Immediate aligned candidate pairs | Next-phrase hits |',
          '|---|---:|---:|---:|---:|---:|---:|---:|---:|']
for d,r in zip(dicts,boundaries):
    union=d['distinct_a']+d['distinct_b']-d['intersection']
    lines.append(f"| {d['boundary']}→{d['boundary']+1} | {d['distinct_a']:,} | {d['distinct_b']:,} | {d['intersection']:,} | {d['intersection']/union:.3%} | {d['shared_occurrences_b']/d['occurrences_b']:.3%} | {d['shared_bytes_b']/d['covered_bytes_b']:.3%} | {r['aligned_phrase_pairs']/r['both']['count']:.3%} | {r['reached_next_phrase_pairs']/r['both']['count']:.3%} |")
lines += ['', 'Dictionary sets include only fully contained occurrences from the global PFP',
          'parse. These are exact interior overlap counts, not independently reset chunk',
          'parse results. Occurrence bytes use phrase length minus the overlap window.',
          '“Immediate aligned” requires the same canonical phrase ID and within-phrase',
          'offset; “next phrase” requires matching next-trigger distance inside the LCE',
          'and the same next phrase ID. The two hit classes can overlap.', '',
          '## Conditional cost model', '',
          f'- Weighted two-candidate mean: {mean_pair:.6f} symbols/B run; sampling standard error {se:.6f}.',
          f'- Weighted largest candidate mean: {mean_best:.6f} symbols/B run.',
          f'- At R=4.8e11 and one comparison stage: {R*mean_pair:.6g} two-candidate symbols.',
          f'- At hypothetical sustained 1e8 / 1e9 symbol comparisons per second: {R*mean_pair/1e8/86400:.3f} / {R*mean_pair/1e9/86400:.3f} days, excluding all other work.',
          f'- Actual selection used {mean_queries:.3f} LCE calls and {mean_probes:.3f} hash equality probes/B head; weighted search-only LCE sum {mean_search:.3f}.',
          f'- Linear scaling of this fragment implementation\'s measured query rate alone: {R*seconds_per_head/86400:.3f} single-core days.',
          f'- Queries exceeding full direct verification: {model["not_fully_verified_queries"]:,}; candidate comparisons touching a local seam: {model["seam_candidate_pairs"]:,}.',
          f'- Immediate phrase shortcuts cover {model["aligned_phrase_pair_fraction"]:.5%} of candidate pairs and {model["aligned_phrase_bytes_fraction_of_pair_LCE"]:.3%} of total candidate LCE symbols; next-phrase bytes cover {model["next_phrase_bytes_fraction_of_pair_LCE"]:.3%} separately (overlap prevents adding these).',
          f'- If a boundary records zero >1M observations, its one-sided 95% event-probability bound is {model["per_boundary_zero_tail_95_upper"]:.8g} under IID uniform B-run sampling.', '',
          'These numbers are conditional arithmetic, not a pile runtime prediction.',
          ('All sampled LCE answers were fully directly verified.' if not model['not_fully_verified_queries'] else 'Some sampled LCE answers remain hash proposals; see the verification counter.'),
          'Sampling error does not cover corpus shift, a missed heavy tail,',
          'or endpoint/row differences. There is no distribution-free tight upper bound',
          'on the mean from this sample. Pair observations are correlated; confidence',
          'calculations use the sampled B head as the unit. Fragment local cycles do',
          'not certify concatenation order. Output run splitting and all merge levels',
          'must be charged separately. See `DESIGN.md` for the statement lock.', '']
(HERE/'RESULTS.md').write_text('\n'.join(lines))
print(json.dumps(model, indent=2))
print('SUMMARY_PASS boundaries=15 dictionary_pairs=15 budgets_and_histograms_checked=1')
